// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH3sI1LiXqPwXRhD3hDpOSG1wh_oXK66A',
    appId: '1:615170747522:web:f97c2d6623172cbcce589b',
    messagingSenderId: '615170747522',
    projectId: 'jobcv-9a173',
    authDomain: 'jobcv-9a173.firebaseapp.com',
    storageBucket: 'jobcv-9a173.appspot.com',
    measurementId: 'G-V5YDYMDVE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdDY6uWpt5xOk4gUF-g11plqzgKRfgFcQ',
    appId: '1:615170747522:android:9a0ae33ec1a4e387ce589b',
    messagingSenderId: '615170747522',
    projectId: 'jobcv-9a173',
    storageBucket: 'jobcv-9a173.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwt5mLrEr-QfoJo_yBZtc7GPBisXk7FzU',
    appId: '1:615170747522:ios:28d3438d0bda39d5ce589b',
    messagingSenderId: '615170747522',
    projectId: 'jobcv-9a173',
    storageBucket: 'jobcv-9a173.firebasestorage.app',
    iosClientId: '615170747522-9nd4sbhe586nac28lrk6hggnho2aj676.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwt5mLrEr-QfoJo_yBZtc7GPBisXk7FzU',
    appId: '1:615170747522:ios:28d3438d0bda39d5ce589b',
    messagingSenderId: '615170747522',
    projectId: 'jobcv-9a173',
    storageBucket: 'jobcv-9a173.appspot.com',
    iosClientId:
        '615170747522-9nd4sbhe586nac28lrk6hggnho2aj676.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}